#! /usr/bin/env sh

usage()
{
	cat <<EOF
Usage: $(basename "${0}") [OPTION...] <NEWNAME> <OLDNAME> <STREETADDRESS> <TOWN/CITY> <POSTCODE> <COUNTY>

Options:
  -h        Print this help text
  -v        Print version information

EOF
}

version()
{
	local version="1.2.0"
	cat <<EOF
make-deedpoll v${version}
Copyright © 2017 - 2018 scherzoso

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

EOF
}

while getopts ":hv" opt; do
	case "${opt}" in
	h)
		usage
		exit 0
		;;
	v)
		version
		exit 0
		;;
	*)
		printf "fatal: invalid option: %s\\n" "${OPTARG}" >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

if [ ! $# -eq 6 ]; then
	printf "fatal: 6 arguments required\\n" >&2
	usage >&2
	exit 2
fi

# Get arguments
newname="${1:-NEWNAME}"
oldname="${2:-OLDNAME}"
streetaddress="${3:-STREETADDRESS}"
towncity="${4:-TOWNCITY}"
postcode="${5:-POSTCODE}"
county="${6:-COUNTY}"

# substitute arguments
sed -i \
	-e "s/NEWNAME/${newname}/" \
	-e "s/OLDNAME/${oldname}/" \
	-e "s/STREETADDRESS/${streetaddress}/" \
	-e "s/TOWNCITY/${towncity}/" \
	-e "s/POSTCODE/${postcode}/" \
	-e "s/COUNTY/${county}/" \
	./deed-poll.tex

# make with pdflatex
printf "Compiling with latexmk...\n" >&2
latexmk --pdflua ./deed-poll.tex 2>&1 \
	| grep -E 'Underfull|Overfull|Warning|Error' >&2

# return to original form
sed -i \
	-e "s/${newname}/NEWNAME/" \
	-e "s/${oldname}/OLDNAME/" \
	-e "s/${streetaddress}/STREETADDRESS/" \
	-e "s/${towncity}/TOWNCITY/" \
	-e "s/${postcode}/POSTCODE/" \
	-e "s/${county}/COUNTY/" \
	./deed-poll.tex
rm -f ./*.[!tp]*
