#! /usr/bin/env sh
# -----------------------------------------------------------------------------


semver="2.0.0"


# Functions
# -----------------------------------------------------------------------------

usage()
{
	printf "usage: make-deedpoll [-h|-v] <args>\\n"
}

more_info()
{
	cat <<EOF
Arguments: (Processed in this order)
 <new_name>    - The name you are adopting
 <old_name>    - The name you are denouncing
 <address>     - Your street adress
 <city>        - Your city
 <postcode>    - Your postcode
 <county>      - Your county

Options:
 -h    - Print this help text
 -v    - Print version information

EOF
}

version()
{
	printf "make-deedpoll v%s\\n" "${semver}"
}


# Script
# -----------------------------------------------------------------------------

while getopts ":hv" opt; do
	case "${opt}" in
	h)
		usage
		more_info
		exit 0
		;;
	v)
		version
		exit 0
		;;
	*)
		printf "fatal: invalid option: %s\\n" "${OPTARG}" >&2
		usage >&2
		exit 1
		;;
	esac
done
shift $((OPTIND - 1))

if [ ! "${#}" -eq 6 ]; then
	printf "fatal: arguments required\\n" >&2
	usage >&2
	exit 1
fi

NEWNAME="${1:-NEWNAME}"
OLDNAME="${2:-OLDNAME}"
ADDRESS="${3:-STREETADDRESS}"
CITY="${4:-TOWNCITY}"
POSTCODE="${5:-POSTCODE}"
COUNTY="${6:-COUNTY}"

make pdf \
	COUNTY="${COUNTY}" \
	NEWNAME="${NEWNAME}" \
	OLDNAME="${OLDNAME}" \
	POSTCODE="${POSTCODE}" \
	ADDRESS="${ADDRESS}" \
	CITY="${CITY}"
